export const WORD_LOADING = "WORD_LOADING";
export const WORD_LOADING_SUCCESS = "WORD_LOADING_SUCCESS";
export const WORD_LOADING_FAILURE = "WORD_LOADING_FAILURE";

export const IMAGE_LOADING = "IMAGE_LOADING";
export const IMAGE_LOADING_SUCCESS = "IMAGE_LOADING_SUCCESS";
export const IMAGE_LOADING_FAILURE = "IMAGE_LOADING_FAILURE";
